### ISSUE TITLE
Helloworld example - cannot establish call

### ISSUE THREAD

**Issue by mehturt** [RestComm/restcomm-android-sdk#281] opened 2016-04-07 20:38 UTC
I'm trying out the latest Android SDK and the helloworld client.
I was able (with some modifications) to establish call between two linphone.org accounts, however when the remote picks up the call, I get this error in the log:
```
04-07 22:34:44.142 19008-19204/com.telestax.restcomm_helloworld E/WEBRTC: ERROR     ; (22:34:44:146 |    0)        VOICE:    1    99;     19204; GetRecCodec() failed to get received codec (error=8111)
04-07 22:34:44.142 19008-19205/com.telestax.restcomm_helloworld W/libjingle: Session description must have DTLS fingerprint if DTLS enabled.
04-07 22:34:44.142 19008-19205/com.telestax.restcomm_helloworld E/libjingle: Failed to set remote answer sdp: Called with SDP without DTLS fingerprint.
04-07 22:34:44.147 19008-19205/com.telestax.restcomm_helloworld E/PCRTCClient: Peerconnection error: setSDP error: Failed to set remote answer sdp: Called with SDP without DTLS fingerprint.
04-07 22:34:44.147 19008-19008/com.telestax.restcomm_helloworld E/RCConnection: PeerConnection error: setSDP error: Failed to set remote answer sdp: Called with SDP without DTLS fingerprint.
```
Any idea what it means?
Thanks.
m.

**Comment by mehturt** [comment] 2016-04-08 06:59
Calling my getonsip.com account works fine though.

**Comment by atsakiridis** [comment] 2016-04-08 08:55
Android SDK uses webrtc for media which means that the SDP of the peer needs to have a DTLS fingerprint. Does the peer of hello world support webrtc? If so it should sent the fingerprint in the SDP. Here's an example (check the last field):

```
v=0
o=- 6712952445337310614 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS ARDAMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 102 0 8 106 105 13 127 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:414680299 1 udp 2122260223 192.168.2.43 63750 typ host generation 0
a=candidate:414680299 2 udp 2122260222 192.168.2.43 53376 typ host generation 0
a=candidate:4003986751 2 udp 1686052606 5.55.247.149 53376 typ srflx raddr 192.168.2.43 rport 53376 generation 0
a=candidate:1446279195 1 tcp 1518280447 192.168.2.43 53157 typ host tcptype passive generation 0
a=candidate:1446279195 2 tcp 1518280446 192.168.2.43 53158 typ host tcptype passive generation 0
a=candidate:4003986751 1 udp 1686052607 5.55.247.149 63750 typ srflx raddr 192.168.2.43 rport 63750 generation 0
a=ice-ufrag:jDJmj/6Yh8xYawJs
a=ice-pwd:vZpi/+TaWLRNn1Ke8XMm75Qm
a=fingerprint:sha-256 0E:92:63:00:9B:DC:F0:E5:57:2C:85:FB:DB:3A:FE:B4:5D:4F:35:40:F8:AA:89:79:B0:C3:6F:1D:A0:0E:F9:76
...
```

**Comment by mehturt** [comment] 2016-04-08 09:33
Thanks, I don't know whether the peer supports it.
This example - what SIP message is it from?

**Comment by atsakiridis** [comment] 2016-04-08 09:54
This is from an invite from our Olympus iOS client utilizing the restcomm-ios-sdk

**Comment by mehturt** [comment] 2016-04-08 09:56
Hm, I thought by peer you mean the B-party of the call.
I have the a=fingerprint: in the the INVITE sent by hello world client.

**Comment by atsakiridis** [comment] 2016-04-08 12:19
Can you provide more details on the scenario? I assume that hello world is the caller, but who is the callee? Also can you provide a tcpdump capture to see the call setup in detail?

Thanks

**Comment by mehturt** [comment] 2016-04-08 12:26
I modified hello world to call from my linphone.org account 1 to my linphone.org account 2. Maybe it's not intended to work like this, but it works from my linphone.org account 1 to my getonsip.com account.

**Comment by atsakiridis** [comment] 2016-04-08 13:04
Well, need to check the tcpdump capture to investigate, so place collect and upload

**Comment by mehturt** [comment] 2016-04-08 20:56
Attached.
[sip.cap.gz](https://github.com/RestComm/restcomm-android-sdk/files/210841/sip.cap.gz)

**Comment by atsakiridis** [comment] 2016-04-11 10:16
Hi @mehturt, just did some investigation on the traffic you sent:
* I see aaaaa registering from Hello World (Restcomm Android SDK)
* Then I see a call from aaaa -> bbbbb
* The problem is in the response from bbbbb, the SDP answer doesn't seem to support webrtc. No DTLS fingerprint is there, no ICE candidates, etc. So here, I think lies your problem: LinphoneAndroid doesn't seem to support webrtc for media (at least in the current configuration) and Hello World only supports webrtc for media.

**Comment by mehturt** [comment] 2016-04-11 13:04
Thanks, makes sense.

**Comment by atsakiridis** [comment] 2016-04-11 13:13
Closing issue per discussion

**Closed by atsakiridis** 2016-04-11 13:13 UTC

**Comment by abrutsze** [comment] 2018-09-13 13:26
Hello, I am having exactly the same issue. Have you figured out any solution ? Why does the same restcomm sdk sends DTLS data when I use restcomm extensions and does not send when I use my custom one ?
