### ISSUE TITLE
Crash when terminating call

### ISSUE THREAD

**Issue by mehturt** [RestComm/restcomm-android-sdk#287] opened 2016-04-15 09:31 UTC
I'm making a video call from my app (similar to hello world example) to my other getonsip account running in a web browser.
I can establish the call, with video just fine, however when terminating the call on the phone, I always get a crash caused by signal 11:
`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x61743b5a in tid 525 (app)`
The crash happens somewhere inside this call:
`remoteVideoTrack.removeRenderer(remoteVideoRenderer);`
Any idea how to diagnose this further?
Thanks.

**Comment by atsakiridis** [comment] 2016-04-19 12:17
Don't you get a stack for the crash to pin point better the cause? Also, does the whole app crash or just the Call Activity?

**Comment by mehturt** [comment] 2016-04-19 20:35
There was no stack trace. Not sure about the app vs call activity, how do I know that?

**Comment by atsakiridis** [comment] 2016-04-20 09:00
Ok, is this reproducible always? Seems like it has issues when removing the video renderer. If just the call activity crashes, then the main activity should remain intact

**Comment by mehturt** [comment] 2016-04-22 07:03
There is no stack trace. The whole app crashes, there's an information box on the phone saying "Unfortunately, XXX has stopped".
This only happens when I select "H264" as the video codec in RCConnection, when creating the PeerConnectionParameters() class.  With the default "VP8" it does not crash.
I am testing with H264 because that's the only codec my remote peer supports, but not sure if this is the correct way to select the codec (see issue #288).

**Comment by atsakiridis** [comment] 2016-04-22 18:08
Wait, so the crash only happens with h.264? And you do get video properly for the duration of the call using h.264 but in the end it crashes?

**Comment by mehturt** [comment] 2016-04-25 06:53
Hm, actually I tested now even with VP8 it crashes.

**Comment by atsakiridis** [comment] 2016-11-24 09:16
@mehturt, sorry for delayed reply. We have integrated with latest webrtc lib, and I believe I tried using H264 in my tests without issues the last couple of months, so it should work now. Can you please retry.

Closing for now, feel free to reopen is you have any issues

**Closed by atsakiridis** 2016-11-24 09:16 UTC
